### ISSUE TITLE
Error when deploying to production in Rails 5

### ISSUE THREAD

**Issue by hgani** [drapergem/draper#755] opened 2016-07-24 13:27 UTC
Hi,

I am getting the following error when deploying to production server:

```
remote:        NameError: uninitialized constant ActionController::TestRequest
remote:        /tmp/build_c921c5050ebe0693cf4cd93b38e9b5d4/vendor/bundle/ruby/2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:41:in `block in controller'
remote:        /tmp/build_c921c5050ebe0693cf4cd93b38e9b5d4/vendor/bundle/ruby/2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:40:in `tap'
remote:        /tmp/build_c921c5050ebe0693cf4cd93b38e9b5d4/vendor/bundle/ruby/2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:40:in `controller'
```

This is using draper-3.0.0.pre1 in Rails 5.

Thanks

**Comment by seanlinsley** [comment] 2016-07-24 18:25
That was caused by some removed code: https://github.com/drapergem/draper/commit/5d9e6919c4736fa31d7fdf4770e326f621bf7e76#diff-a8e206117ed83e6691706a055f946081L41

What exactly is your setup, where TestRequest isn't loaded? I removed the `defined?` check because the tests didn't fail, but apparently it is needed.

**Comment by hgani** [comment] 2016-07-24 23:55
@seanlinsley Thanks for the quick response

It seems that the error is happening during asset precompilation.

Some parts of our javascript code is dynamically generated so we have files such as example.js.erb 

The .js.erb files contain Rails code that helps generate the final javascript file, some of this code might be using my presenters (which uses draper).

**Comment by hgani** [comment] 2016-07-25 12:02
Additional information: the error is also happening in some of my background (Sidekiq) workers.

**Comment by clemens** [comment] 2016-07-25 15:19
I'm running into a similar issue: Sometimes (but not always) one of my ActiveJobs raise the same error. Since this seems to be code that (presumably) only applies to the test environment, shouldn't it be run only in the test environment rather than development, production etc.?

**Comment by hgani** [comment] 2016-07-29 08:45
For those running into a similar issue, you can use my fork for the time being: https://github.com/hgani/draper

Put this in your Gemfile:
`gem 'draper', git: 'https://github.com/hgani/draper.git'`

**Comment by steakknife** [comment] 2016-11-02 02:51
@hgani 
```ruby
gem 'draper', github: 'hgani/draper'
```
For security, since bundler 1.x is insecure by default:

```ruby
# near top of Gemfile
git_source(:github) { |r| r += "/#{r}" if r !~ /\//; "https://github.com/#{r}.git" }
```

**Comment by fbatista** [comment] 2016-12-06 15:55
Could we get this merged ? It breaks when a decorator is loaded in the context of a background worker, for example taking care of email etc.

**Comment by seanlinsley** [comment] 2017-01-15 21:33
@fbatista no one actually opened a PR. Feel free to do that yourself.

**Comment by hgani** [comment] 2017-01-16 10:50
Someone has made a pull request to address the same issue here: https://github.com/drapergem/draper/pull/763

**Comment by McRip** [comment] 2017-01-16 12:33
i just rebased it.

**Comment by hgani** [comment] 2017-01-16 22:18
Good job. Thanks @McRip

**Comment by jaspertandy** [comment] 2017-01-30 10:08
Any ideas when this is going to get merged, or should we keep using hgani's fork in Rails 5?

**Comment by seanlinsley** [comment] 2017-02-21 15:56
I've merged #763. Can someone confirm it's working as expected?

**Comment by McRip** [comment] 2017-02-22 07:44
It is working for me.

**Comment by seanlinsley** [comment] 2017-02-22 18:12
Thanks for confirming @McRip. Once the other Rails 5 issues are fixed, I'll publish a new Rubygems release.

**Closed by seanlinsley** 2017-02-22 18:12 UTC
