### ISSUE TITLE
Update actionpack version to support Rails 5.1

### ISSUE THREAD

**Issue by abali96** [drapergem/draper#808] opened 2017-05-20 23:19 UTC
When trying to upgrade to Rails 5.1, I receive this error:
```
In Gemfile:
    draper (~> 3.0.0) was resolved to 3.0.0, which depends on
      actionpack (~> 5.0)
    rails (>= 5.1) was resolved to 5.1.0, which depends on
      actionpack (= 5.1.0)
```

I'm currently on draper 3.0.0.

**Comment by syguer** [comment] 2017-05-22 04:34
`~> 5.0` means `5.x` (not 5.0.x). So it looks something weird for me.
And I tried on my local environment, could not be reproduced.
Please try `bundle update rails` again after `gem update bundler`.

**Comment by maschwenk** [comment] 2017-06-15 22:23
Hi, @syguer I believe you are incorrect. See http://bundler.io/v1.5/gemfile.html#gemfiles
![image](https://user-images.githubusercontent.com/1264305/27204206-95ffed90-51de-11e7-9c53-65259e63b97c.png)

**Comment by maschwenk** [comment] 2017-06-15 22:26
You can even reference http://jubianchi.github.io/semver-check/ if you don't trust that

**Comment by syguer** [comment] 2017-06-19 02:28
Thanks for reference 👍 
Your reference says, 

> `~> 2.1` is identical to `>= 2.1` and `< 3.0`. 

So `~> 5.0` means `>= 5.0 and < 6.0`, doesn't this?
Please try `bundle udpate rails draper`, and let me show your Gemfile.lock if you can.

**Comment by joeljunstrom** [comment] 2017-06-26 09:40
@syguer I think `~> 5.0` means `>= 5.0.0 and < 5.1`. Easily tested by http://jubianchi.github.io/semver-check/ as stated above.

**Comment by syguer** [comment] 2017-06-27 06:51
OK. I've created repository to try reproducing.
[Here](https://github.com/syguer/reproduce_draper_compatibility/blob/master/Gemfile.lock) is Gemfile.lock. It was passed.

My opinion is refer to http://bundler.io/v1.5/gemfile.html#gemfiles.

> ~> 2.1 is identical to >= 2.1 and < 3.0.

So this means 

* Documentation of bundler is wrong

or

* SemVer Check is wrong on Bundler

**Comment by codebycliff** [comment] 2017-06-28 15:45
I believe @syguer is correct. The [documentation on bundler's site](http://bundler.io/gemfile.html#gemfiles) clearly states that `~> 5.0` means `>= 5.0 and < 6.0` via this example:

> ~> 2.1 is identical to >= 2.1 and < 3.0

If we specified the patch number (i.e. `~ 5.0.0`), that would in fact mean `>= 5.0.0 and < 5.1.0` like the rest of you are stating. You can verify this is the case on [RubyGem's documentation](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) where it states:

![image](https://user-images.githubusercontent.com/651946/27645286-54cbabe0-5beb-11e7-9380-a8dcd89774cf.png)

Here are a couple more sources verifying this is the case:

https://robots.thoughtbot.com/rubys-pessimistic-operator
https://depfu.io/blog/2016/12/14/get-to-know-your-twiddle-wakka


As far as the [http://jubianchi.github.io/semver-check/](semver-check) utility you guys are referencing, it is a general utility for semver trying to solve several dependency manager's interpretations of it. I believe it is incorrect for the case of Bundler at the very least. The `~>` is unique to bundler and doesn't even exist in the NPM / Composer world. It has been broken out into two different operators `~` and `^` to avoid this confusion. Furthermore, after looking at [the source code for that utility](https://github.com/jubianchi/semver-check/blob/master/src/libs/semver-constraint.js), it doesn't look like they even support the `~>` operator in their checks. I will open an issue on their repository asking them to support the `~>` operator to avoid this confusion in the future.

@abali96 I'm not doubting you received that error message, but both @syguer and I haven't been able to reproduce the issue. Can you give me more detail on how you are coming across this? For instance what bundler version are you running and what does your `Gemfile` look like? Are you upgrading by manually modifying the `Gemfile` or running `bundle update rails`?

**Comment by codebycliff** [comment] 2017-06-29 17:47
The http://jubianchi.github.io/semver-check/  utility has been updated to support the `~>` operator. You should be able to verify the supported versions on that site now.

**Comment by maschwenk** [comment] 2017-06-29 18:17
Hahah awesome. Thanks for your extremely thorough response. I just recently upgraded to Rails 5.1 and Draper upgrade worked fine. Not exactly sure what the cause was earlier, maybe I was actually on the `beta` at the time.

**Comment by codebycliff** [comment] 2017-07-05 17:27
Sounds good. I am going to close this for now then.

@abali96 If you still run into this issue, please comment on the issue and I will open it back up / look into it.

**Closed by codebycliff** 2017-07-05 17:27 UTC
Labels: awaiting response
