### ISSUE TITLE
rake commands fail if using rails 5

### ISSUE THREAD

**Issue by yltsrc** [drapergem/draper#681] opened 2015-06-28 10:14 UTC
```
$ rake spec
rake aborted!
LoadError: cannot load such file -- rails/test_unit/sub_test_task
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/gems/draper-2.1.0/lib/draper/tasks/test.rake:7:in `require'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/gems/draper-2.1.0/lib/draper/tasks/test.rake:7:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `load'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `block (2 levels) in <class:Railtie>'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `block in <class:Railtie>'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/railtie.rb:237:in `instance_exec'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/railtie.rb:237:in `block in run_tasks_blocks'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/railtie.rb:245:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/railtie.rb:245:in `each_registered_block'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/railtie.rb:237:in `run_tasks_blocks'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/application.rb:442:in `block in run_tasks_blocks'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/engine/railties.rb:13:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/engine/railties.rb:13:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/application.rb:442:in `run_tasks_blocks'
/home/vagrant/.rvm/gems/ruby-2.2.2@rails_5.0/bundler/gems/rails-1022796ac075/railties/lib/rails/engine.rb:460:in `load_tasks'
/home/vagrant/test_app/rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by yltsrc** [comment] 2015-06-28 10:17
example Gemfile
```
source 'https://rubygems.org'
gem 'rails', github: 'rails/rails'
gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'arel', github: 'rails/arel'
gem 'sqlite3'
gem 'draper'
```

**Comment by audionerd** [comment] 2015-10-08 16:41
In [test.rake](https://github.com/drapergem/draper/blob/57a514133bc241e74cc4e8877d014cad4e1f12c6/lib/draper/tasks/test.rake) Draper requires `rails/test_unit/sub_test_task`, but [Rails 5 does not have that file in `railties/lib/rails/test_unit`](https://github.com/rails/rails/tree/0d4aa374a2d3358c79d2e3f83e1327bc7c81fa1d/railties/lib/rails/test_unit) anymore. 

It was removed by [3297909](https://github.com/rails/rails/commit/3297909cdc4fb114df96b0e74ff5d55c210650cf#diff-6a1093c8397b2b61b6590baf91a9601b) (see also: [8017e6a](https://github.com/rails/rails/commit/8017e6af31caa58a58787274ff0ca01397219e49)).

**Comment by asiniy** [comment] 2015-11-07 14:27
@audionerd do you have any plans regarding send pull request of your 'rails5' branch to the master branch of this repo?

**Comment by audionerd** [comment] 2015-11-07 18:21
@asiniy No, sorry, I haven't had time to dig further into Rails 5 support for Draper. My current branch was just a quick hack that "worked for me", but I didn't do any further testing.

**Comment by mayank-istar** [comment] 2015-12-24 08:06
can any one tell me how to resolve this error.

**Comment by jasnow** [comment] 2015-12-24 14:19
@mayank-istar - Try "gem 'draper', github: 'audionerd/draper', branch: 'rails5'"

**Comment by seanlinsley** [comment] 2015-12-24 20:49
@audionerd are you planning on opening a pull request?

**Comment by dmitry** [comment] 2015-12-27 20:08
@audionerd would be great to see it get merged.

**Comment by ivanjolic95** [comment] 2016-03-22 15:17
I can't pull draper from github because I'm using it in an engine as a dependency. Are there any plans to add official Rails 5 support?

**Comment by jasnow** [comment] 2016-03-22 15:19
@ivanjolic95 : Did you try gem 'draper', github: 'audionerd/draper', branch: 'rails5'

**Comment by ivanjolic95** [comment] 2016-03-22 15:31
I can't really use any fork because I cannot pull gems from github in engine's .gemspec file. I've tried to put it in the gemfile and it doesn't work.

**Comment by Mehonoshin** [comment] 2016-04-06 23:02
Hi, folks!
I'm currently collecting all Rails 5 related fixes in single branch.
But we need an active maintainer to merge it and release new draper version.

**Comment by chulkilee** [comment] 2016-05-18 20:39
Instead of using forked version of draper, you can do monkey patch like this:

```ruby
# lib/rails/test_unit/sub_test_task.rb
class Rails::SubTestTask < Rake::TestTask
end
```

**Comment by JohnSmall** [comment] 2016-09-22 17:12
How come this is tagged as Closed and Merged when it very clearly isn't?

I've just created a new Rails 5 project and get this exact error.

**Comment by kyledecot** [comment] 2016-09-29 18:28
My team is also receiving this error on various projects when attempting to move to Rails 5. Any progress on getting this fixed (without monkey patching)?

**Comment by danielricecodes** [comment] 2016-10-10 19:02
@JohnSmall @kyledecot - same.  Brand new Rails 5 project and just `gem 'draper'` in Gemfile.  Using the fork seemed to work though.

**Comment by asiniy** [comment] 2016-10-11 03:35
Guys, feel free to switch to the `gem 'drape'`. It's a draper designed for rails 5.

**Comment by dmitry** [comment] 2016-10-11 08:29
@asiniy do you mean https://github.com/MrEmelianenko/drape? It's not developed for the last 5 months, how can anyone be sure it will be maintained in the future?

**Comment by rafaelsales** [comment] 2016-12-27 07:06
omg, that's lame.

**Comment by keithmattix** [comment] 2017-01-12 00:14
Still no solution for this? `drape` hasn't been updated in 8 months...

**Comment by dmitry** [comment] 2017-01-12 09:19
Checkout https://github.com/drapergem/draper/issues/772

**Comment by seanlinsley** [comment] 2017-01-15 21:47
Could someone please open a PR?

**Comment by plodshooter** [comment] 2017-01-26 10:20
So, the issue is 1,5 years old and there is still no fix for that? Except the monkey patch and forked repos, of course...

**Comment by MatthiasRMS** [comment] 2017-02-02 10:52
Use:
gem 'draper', "3.0.0.pre1"

Not a fork and not a monkey patch. Seems to be the "best" solution right now.

**Comment by Irostovsky** [comment] 2017-02-03 14:29
It works with rails 5, thank you @MatthiasRMS

**Comment by sanchojaf** [comment] 2017-02-21 19:05
Hi, same issue with gem 'rails', '~> 5.0.1' 

And gem 'draper' is not working for me, I try master, rails5 branch, 3.0.0.pre1

**Comment by codebycliff** [comment] 2017-03-29 19:44
Is this still an issue in master?

**Comment by codebycliff** [comment] 2017-03-31 03:09
I believe this is no longer an issue. Please correct me if I'm wrong and I'll take a look into it.

**Closed by codebycliff** 2017-03-31 03:09 UTC

**Comment by kyledecot** [comment] 2017-04-17 17:11
@codebycliff Is a new version going to be released on rubygems?

**Comment by codebycliff** [comment] 2017-04-17 19:49
@kyledecot Yes, soon.. I'm hoping to have a release in the next couple weeks.
